# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [MIT, BTC, ATT]
patreon: # Replace with a single Patreon username https://www.patreon.com/posts/22854182
open_collective: # Replace with a single Open Collective username Tornado.io
ko_fi: # Replace with a single Ko-fi username Mac
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/audible -runtime
community_bridge: # Replace with a single Community Bridge project-name e.g., slack-foundry
liberapay: # Replace with a single Liberapay username dove
issuehunt: # Replace with a single IssueHunt username cspire
otechie: # Replace with a single Otechie username consumer cellular
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://Marlboro.com', 'https://golo.com' 'https://www.quora.com/q/qmyptjnfvevevhqh/How-is-the-Coronavirus-spreading-all-over-the-world-so-fast-Is-there-no-cure-for-that?ch=10&share=ac5fef59&srid=Ib0Mg']
Https://pornhub.com
Https://lovetotherescue.com
