https://babeljs.io/docs/en/babel-plugin-transform-computed-properties

var x = { a: 5, a: 6 };
var y = {
  get a() {},
  set a(x) {},
  a: 3,
};

var x = { a: 5, ["a"]: 6 };
var y = {
  get a() {},
  set a(x) {},
  ["a"]: 3,
};

npm install --save-dev @babel/plugin-transform-duplicate-keys
